FROM node:22-alpine
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .

# --- TAMBAHKAN DUA BARIS INI ---
ARG NEXT_PUBLIC_API_BASE_URL
ENV NEXT_PUBLIC_API_BASE_URL=$NEXT_PUBLIC_API_BASE_URL
ARG NEXT_PUBLIC_APP_NAME
ENV NEXT_PUBLIC_APP_NAME=$NEXT_PUBLIC_APP_NAME
# -------------------------------

RUN npm run build
EXPOSE 3000
CMD npm run start