name: Deploy Frontend to VPS

on:
  push:
    branches:
      - main # Jalankan deploy otomatis setiap ada push/merge ke branch main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Executing remote ssh commands to deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets::VPS_HOST }}
          username: ${{ secrets::VPS_USER }}
          key: ${{ secrets::VPS_SSH_KEY }}
          port: 22
          script: |
            cd /home/magentaadam/projects/memangkas-barber/sixteen-barber
            git pull origin main
            cd ..
            docker compose up -d --build sixteen-barber